```{r}
#install.packages("rpart.plot")
library(rpart)
library(rpart.plot)
library(caret)
```

```{r}
setwd("D:/Labs/Data Science/Tree")
df <- read.csv("survey.csv", header = TRUE, sep = ",")
train <- head(df, 600)
test <- tail(df, 150)
```

```{r}
class_tree <- rpart(formula = MYDEPV ~ Price + Income + Age, data = train, method = "class", parms=list(split="information"))
summary(class_tree)
```

```{r}
printcp(class_tree)
rpart.plot(class_tree, type = 0)
```

```{r}
pred1 <- predict(class_tree, train, type = "class")
confusionMatrix(pred1, as.factor(train$MYDEPV))
```

```{r}
print(paste("MC rate for zero-class: ", 26 / (26 + 314)))
print(paste("MC rate for  one-class: ", 19 / (19 + 241)))
```

```{r}
print(paste("Resubstitution error rate: ", (19 + 26) / (19 + 26 + 314 + 241)))
```

```{r}
#install.packages("ROCR")
library(ROCR)
```

```{r}
#p <- predict(class_tree, train, type = "prob")
#auc <- auc(train$MYDEPV, p[,2])
#predObj <- prediction(p, train$MYDEPV)
#performance(prediction.obj = pred, measure = "tpr", x.measure = "fpr")
#plot(roc(train$MYDEPV, p[,2]))
```

```{r}
#plot.roc()
```

```{r}
pred2 <- predict(class_tree, test, type = "class")
cm2 <- confusionMatrix(pred2, as.factor(test$MYDEPV))
cm2
```

```{r}
print(paste("MC rate for zero-class: ", 10 / (10 + 76)))
print(paste("MC rate for  one-class: ", 6 / (6 + 58)))
```

```{r}
gini_tree <- rpart(formula = MYDEPV ~ Price + Income + Age, data = train, method = "class", parms = list(split = "gini"))
summary(gini_tree)
```

```{r}
printcp(gini_tree)
rpart.plot(gini_tree, type = 0)
```

```{r}
plotcp(gini_tree)
pruned <- prune(tree = gini_tree, cp = 0.01153846)
#pruned <- prune(gini_tree, cp = gini_tree$cptable[which.min(gini_tree$cptable[, "xerror"]), "CP"])
gini_tree$cptable[which.min(gini_tree$cptable[, "xerror"]), "CP"]
```

```{r}
printcp(pruned)
rpart.plot(pruned, type = 0)
```

```{r}
pred3 <- predict(pruned, train, type = "class")
cm3 <- confusionMatrix(pred3, as.factor(train$MYDEPV))
cm3
```

```{r}
paste("MC rate for zero-class: ", 18 / (18 + 322))
paste("MC rate for  one-class: ", 43 / (43 + 217))
paste("Overall: ", 1 - cm3$overall[1])
```
